a:
	 gcc dijkstra.c jval.o dllist.o fields.o jrb.o -o result.exe
	 ./result.exe
b:
	 gcc dijkstraReal.c jval.o dllist.o fields.o jrb.o -o result.exe
	 ./result.exe
c: 
	 gcc test.c jval.o dllist.o fields.o jrb.o -o result.exe
	 ./result.exe
d: 
	gcc practice.c jval.o dllist.o fields.o jrb.o -o result.exe
	 ./result.exe
e:
	gcc thi.c -o result.exe
	./result.exe
