a:
	 gcc docfile3.c jval.o dllist.o fields.o jrb.o -o result.exe
	 ./result.exe
b:
	 gcc thuvien.c jval.o dllist.o fields.o jrb.o -o result.exe
	 ./result.exe
c: 
	 gcc contro.c jval.o dllist.o fields.o jrb.o -o result.exe
	 ./result.exe
d: 
	gcc check.c jval.o dllist.o fields.o jrb.o -o result.exe
	 ./result.exe
e:
	gcc thi.c -o result.exe
	./result.exe
